import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Navigation } from "@/components/Navigation";
import { SoundsStoreProvider } from "@/providers/sounds-store-provider";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-gray-950">
      <body>
        <Providers>
          <SoundsStoreProvider>
            <header className="w-full h-20 flex items-center text-fg z-40">
              <div className="xl:max-w-7xl px-5 sm:px-10 lg:px-5 w-full mx-auto">
                <Navigation />
              </div>
            </header>
            <main className="flex flex-col items-center justify-between pt-10 px-24 text-foreground">
              {children}
            </main>
          </SoundsStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
